version: 2

project_name: typomat

before:
  hooks:
    - go mod tidy

release:
  prerelease: auto

builds:
  - main: ./cmd/typomat
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

brews:
  - name: typomat
    repository:
      owner: vupdivup
      name: homebrew-tap
    homepage: https://github.com/vupdivup/typomat
    description: Turn your code into muscle memory
    license: MIT
    skip_upload: auto

scoops:
  - name: typomat
    repository:
      owner: vupdivup
      name: scoop-bucket
    homepage: https://github.com/vupdivup/typomat
    description: Turn your code into muscle memory
    license: MIT
    skip_upload: auto
